x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/cloudflare-zero-trust.svg
  urls:
    - https://one.dash.cloudflare.com

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run --token ${secrets.CLOUDFLARED_TOKEN}}
    environment:
      - TZ=Asia/Seoul
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true