
services:
  npm_mysql:
    image: 'jc21/mariadb-aria:latest'
    container_name: npm_mysql
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${NPM_DB_ROOT_PASSWORD:?database password required}
      - MYSQL_DATABASE=npm
      - MYSQL_USER=npm
      - MYSQL_PASSWORD=${NPM_DB_PASSSWORD:?database password required}
      - TZ=Asia/Seoul
    volumes:
      - npm_mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - database

  npm:
    image: 'jc21/nginx-proxy-manager:2'
    container_name: npm
    restart: always
    ports:
      - 81:81    # 관리 페이지 (UI)
      - 443:443  # HTTPS 트래픽
    env_file:
      - .env
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    environment:
      - DB_MYSQL_HOST=npm_mysql
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=npm
      - DB_MYSQL_PASSWORD=${NPM_DB_PASSSWORD:?database password required}
      - DB_MYSQL_NAME=npm
      - TZ=Asia/Seoul
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    depends_on:
      - npm_mysql
    networks:
      - database
      - proxy

# 하단에 볼륨 정의 추가
volumes:
  npm_data:
    name: npm_data
  npm_letsencrypt:
    name: npm_letsencrypt
  npm_mysql:
    name: npm_mysql

networks:
  proxy:
    external: true
  database:
    external: true